# Where's mah Swift at Travis!?
language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1
      sudo: required

script:
  - ./Scripts/TravisCI/test.sh

after_success:
  - ./Scripts/TravisCI/code-coverage.sh

